version: "3"
services:
#   app1:
#     build: ./authentication-service/ # caminho para o Dockerfile
#     ports:
#       - "3000:3000" # porta que voce configurou no Dockerfile
#     volumes:
#       - .:/usr/src/authentication-service
#     command: npm start # comando que ira executar assim que subir o container

#   app2:
#     build: ./feed-service/ # caminho para o Dockerfile
#     ports:
#       - "3001:3001" # porta que voce configurou no Dockerfile
#     volumes:
#       - .:/usr/src/feed-service
#     command: npm start # comando que ira executar assim que subir o container

#   app3:
#     build: ./notification-service/ # caminho para o Dockerfile
#     ports:
#       - "3003:3003" # porta que voce configurou no Dockerfile
#     volumes:
#       - .:/usr/src/notification-service
#     command: npm start # comando que ira executar assim que subir o container

#   app4:
#     build: ./api-gateway/ # caminho para o Dockerfile
#     ports:
#       - "3004:3004" # porta que voce configurou no Dockerfile
#     volumes:
#       - .:/usr/src/api-gateway
#     command: npm start # comando que ira executar assim que subir o container

#   app5:
#     build: ./users-service/ # caminho para o Dockerfile
#     ports:
#       - "3005:3005" # porta que voce configurou no Dockerfile
#     volumes:
#       - .:/usr/src/users-service
#     command: npm start # comando que ira executar assim que subir o container

    zookeeper:
      image: wurstmeister/zookeeper:latest
      ports:
        - "2181:2181"
    kafka:
      image: wurstmeister/kafka:2.11-1.1.1
      ports:
        - "9092:9092"
      links:
        - zookeeper
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        KAFKA_DELETE_TOPIC_ENABLE: "true"
        KAFKA_CREATE_TOPICS: "signup:1:1,signup.reply:1:1"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
